GET http://localhost:3000/users/637e1da88fab83ddb99e67f5

###
POST http://localhost:3000/users
Content-Type: application/json

{
  "firstName": "omar",
  "lastName": "omar",
  "age":123
}

###
DELETE http://localhost:3000/users/637def567c6c2bbda5224b2b

###
PATCH  http://localhost:3000/users/637def567c6c2bbda5224b2b
Content-Type: application/json

{
  
  "firstName": "omar",
  "lastName": "mo",
  "age":123
}